#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jchardet
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar
Source0  : https://repo.maven.apache.org/maven2/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar
Source1  : https://repo.maven.apache.org/maven2/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jchardet-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jchardet package.
Group: Data

%description data
data components for the mvn-jchardet package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/jchardet/jchardet/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/jchardet/jchardet/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar
/usr/share/java/.m2/repository/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.pom
